<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="7434" started-at="2019-04-27T17:14:32Z" finished-at="2019-04-27T17:14:39Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="7434" started-at="2019-04-27T17:14:32Z" finished-at="2019-04-27T17:14:39Z">
      <class name="SimpleProgrammer.validateTitle">
        <test-method status="PASS" signature="setup()[pri:0, instance:SimpleProgrammer.validateTitle@12468a38]" name="setup" is-config="true" duration-ms="6997" started-at="2019-04-27T10:14:32Z" finished-at="2019-04-27T10:14:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="Login()[pri:0, instance:SimpleProgrammer.validateTitle@12468a38]" name="Login" duration-ms="79" started-at="2019-04-27T10:14:39Z" finished-at="2019-04-27T10:14:39Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Complex Programmer - Member Forums] but found [Simple Programmer - Member Forums]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Complex Programmer - Member Forums] but found [Simple Programmer - Member Forums]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at SimpleProgrammer.validateTitle.Login(validateTitle.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:SimpleProgrammer.validateTitle@12468a38]" name="teardown" is-config="true" duration-ms="331" started-at="2019-04-27T10:14:39Z" finished-at="2019-04-27T10:14:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- SimpleProgrammer.validateTitle -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
